### ISSUE TITLE
Button to continue browsing after matching

### ISSUE THREAD

**Issue by anthony-ft** [rovrlabs/flirtual#41]
**Is your feature request related to a problem? Please describe.**
Users are confused or want to save time to continue looking at other profiles after matching with someone. Currently there is just a messaging button. Hitting settings and then "browse" is not intuitive and is annoying to people who have lots of potential matches.

**Describe the solution you'd like**
Adding a button to continue looking at other profiles (hacky: maybe just hyperlinked to "Browse" page), in the style of the Undo button, (white, black), that says "Continue", next to the "message" button.

**Describe alternatives you've considered**
A button with an arrow.

**Additional context**
After talking with some people, user behaviour on dating apps seems to be first swiping/matching through available profiles, then messaging matches afterwards. I.e. batching matching and messaging, as opposed to messaging someone right after matching.

**Comment by kfarwell** [comment]
Added in 1b93a10601ddee6c785071dc83b7a649c9f29c00
