### ISSUE TITLE
Hosting is inconsistent and tends to go offline.

### ISSUE THREAD

**Issue by MistressPlague** [rovrlabs/flirtual#47]
**Describe the bug**
The hosting for flirtu.al is inconsistent, constantly going offline at weird times, such as the time of me writing this.

**To Reproduce**
Sadly this is a inconsistency issue.

**Expected behavior**
Speedy GET & POST, etc responses and not even close to as much downtime.

**Screenshots**
![chrome_dKVcj0hR1u](https://user-images.githubusercontent.com/36628963/189093962-c02a96b5-b06b-4f09-8ed1-37af9fd11df6.png)
![image](https://user-images.githubusercontent.com/36628963/189094096-d66043e4-ae7d-46e1-91e3-f7982d1f2a14.png)

**Environment (please complete the following information):**
First screenshot: Windows 10, Google Chrome.
Second screenshot: Google Pixel 2, Flirtu.al app.

**Comment by MistressPlague** [comment]
Addition screenshot from right now: 
![chrome_r51LokaJLb](https://user-images.githubusercontent.com/36628963/189094352-9675d50e-d9ca-47d3-b728-65405a6f2726.png)

**Comment by kfarwell** [comment]
We're currently experiencing some intermittent issues with an upstream database provider as a result of heavy traffic.

Closing as these issues aren't related to this repo but we're working to get them resolved ASAP. Thanks for your patience.
